services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: porocar
      POSTGRES_USER: porocar
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  mqtt:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
      - "9001:9001"

  # Optional: Redis für caching
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  db_data: