package com.porotech.backend.model;

public enum EventType {
    CAR_INITIALIZED,
    CONNECTION_ESTABLISHED,
    CONNECTION_LOST,
    CAMERA_STREAM_STARTED,
    CAMERA_STREAM_STOPPED,
    BATTERY_LOW,
    ERROR_OCCURRED,
    DRIVE_TO_POINT,
    ARRIVAL_AT_DESTINATION
}
